server:
  port: 8081

#MariaDB
spring:
  profiles: default
  datasource:
    hikari:
      dirver-class-name: org.mariadb.jdbc.Driver
      jdbc-urlurl: jdbc:mariadb://${DB_URL}/pv_ess
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    #      jdbc-url: jdbc:mariadb://172.16.10.143:13007/pv_ess
    #      username: pms
    #      password: pmsPMS2018@#$

---
spring:
  publicKeyString: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDLfWTefQbvzZBauNdKhpOnXdYTYxzvG1Mq3nUHtJ6XekIzOxxqbDHVHQTqLZB3jdbpIFU+dQqMPGTHyG5/Sdn+XNMXNUW9rka4l4nqZ99Pxiev+pYvtPEIwj/ioZG5NsVrMJzc0VDzD0JrE6BN1wJeLJJX2oXn3og2hlBgfu19KQIDAQAB
  privateKeyString: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMt9ZN59Bu/NkFq410qGk6dd1hNjHO8bUyredQe0npd6QjM7HGpsMdUdBOotkHeN1ukgVT51Cow8ZMfIbn9J2f5c0xc1Rb2uRriXiepn30/GJ6/6li+08QjCP+Khkbk2xWswnNzRUPMPQmsToE3XAl4sklfahefeiDaGUGB+7X0pAgMBAAECgYBaMvkVTiJXBa2pKSn1VPX6SDPuYA6hRmF1LSp/AecSihTyFI+h9NeZ+cUF8LCK7gqHR9fBWawVQWgCzqt8LMY9mXwJTn5XqbX+KYr/zagQ7o5eTasQo2vEEhGnYPAoh7xMWgj3MRuwrye/SiKD6L4mAhUoaRNmjRXY8FCSJPmmAQJBAOxpLe0hJF4cbVY4Rk0/plqO7asiiXBapfB0Hj61bU0gd5u6DlKcZup3WbUXBpvZy1iKvcD/VqwhRuL5KhyCX0kCQQDcWeIjnCD4fCUDchgRve+dRP+b6eQ2+kClgd8MGQlGOFREqfk3fkzYfeKPE51jOBgoXyPRVhEqibWmrROLU87hAkEAmZ63IzG4Chd6zN4AgM3tcUcTFXN5z7J3xcoOpT0La2S/lEfQasoK7izj9BKkTr21rzFooHLLhUqSX4b9YE0vUQJAfa42saDnnVMRuXlmCRiQht9H+6HYLRNns/7zPW86Pvb5+YAJSYGcSw7iHkFNz7266av6PfgdKmoJVdv5/cn7gQJAGeopee93HKIKhnUL5CP7ufRMygVQtpEKyld8BsenfwSjloXICkADQz6egTqj5+RbKzsnOBHRHB6dS0xn6bXedg==
  sms:
    kr:
      callbackNumber: qYGsGWRMsfbWenIbdvShMC1bOf6ijuxxtMwog8FzCkSUW2uiavnu8zvkucZvaA6GONJLJzpEkI8/Rb4QfLMsO4OlbxUsUyPKPd+A4hJX80ae9oCYo+BuXHsG0c7oybs+s/PcuPCREcYVBgmI5i4Mh6M7CToewo0skVyn5J+qQqI=
---
#Telegram
spring:
  privateKeyString: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMt9ZN59Bu/NkFq410qGk6dd1hNjHO8bUyredQe0npd6QjM7HGpsMdUdBOotkHeN1ukgVT51Cow8ZMfIbn9J2f5c0xc1Rb2uRriXiepn30/GJ6/6li+08QjCP+Khkbk2xWswnNzRUPMPQmsToE3XAl4sklfahefeiDaGUGB+7X0pAgMBAAECgYBaMvkVTiJXBa2pKSn1VPX6SDPuYA6hRmF1LSp/AecSihTyFI+h9NeZ+cUF8LCK7gqHR9fBWawVQWgCzqt8LMY9mXwJTn5XqbX+KYr/zagQ7o5eTasQo2vEEhGnYPAoh7xMWgj3MRuwrye/SiKD6L4mAhUoaRNmjRXY8FCSJPmmAQJBAOxpLe0hJF4cbVY4Rk0/plqO7asiiXBapfB0Hj61bU0gd5u6DlKcZup3WbUXBpvZy1iKvcD/VqwhRuL5KhyCX0kCQQDcWeIjnCD4fCUDchgRve+dRP+b6eQ2+kClgd8MGQlGOFREqfk3fkzYfeKPE51jOBgoXyPRVhEqibWmrROLU87hAkEAmZ63IzG4Chd6zN4AgM3tcUcTFXN5z7J3xcoOpT0La2S/lEfQasoK7izj9BKkTr21rzFooHLLhUqSX4b9YE0vUQJAfa42saDnnVMRuXlmCRiQht9H+6HYLRNns/7zPW86Pvb5+YAJSYGcSw7iHkFNz7266av6PfgdKmoJVdv5/cn7gQJAGeopee93HKIKhnUL5CP7ufRMygVQtpEKyld8BsenfwSjloXICkADQz6egTqj5+RbKzsnOBHRHB6dS0xn6bXedg==
  telegram:
    api-url: https://api.telegram.org/bot
    token: oW0USF4gKI26xyGTQMnJgWNfD4PFlux56/3L3K1NER2YO2LFC4nwXUH01oc3efT12hHweKmylGfzGadU40wxyTDjnBdbIo8sA8JwbN7l66Xs9ps1hty98hvVO+QeKka9HRGIclj2M+uzSypen8RetfrbRA25wC9eYZclbKlDGEY=

---
logging:
  level:
    root: INFO
  base:
    path: /home/logs
  pattern: "%-5level %d{yy-MM-dd HH:mm:ss} [%logger{0}:%line] - %msg%n"
  file:
    name: pms
    maxsize: 100MB
    maxhistory: 15
---
# Swagger(Custom Properties) : Api Documentation Information 관련 설정
swagger:
  path: /**
  api:
    title: mys-bems API
    # desc: Interface Description
    ver: 1.0.1
  contact:
    name: JeongMin LEE
    url: ""
    email: jminlee@nuriflex.com
  license:
    name: Apache License Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
#  doc: # for External Doc (more info..)
#    desc: RMS Service API Documentation
#    path: /api-doc.html

# springdoc(Official Properties)
springdoc:
  version: 1.0 # 문서버전 = 배포버전
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-ui.html # swagger-ui custom path(redirect)
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - ${swagger.path} # path selector

---
spring:
  activemq:
    broker-url: tcp://172.16.10.143:16011?trace=false&soTimeout=60000
---
spring:
  interface:
    ip: localhost
---
spring:
  mail:
    gmail:
      frommailAdress: nuritelecom.service2@gmail.com
      frommailpasswd: PWnk9dWYXXnbOaYcS18R7DpyAsOfBnNN6ycsCP+hhwchcKTkAiWzPTOZfpVWltLvdd5jHOpjsJDgJypQemPwKL6HXgiONTw+s0D1+B9Pvi1oZ5b0SuHUIfGG0r4m66IarP8EmSggqCgzpkt7yvbByTSFaixo5bBm5buhKGRAFNQ=
    nuri:
      frommailAdress: TEMSSystem@nuriflex.co.kr
      frommailpasswd: l3QuglIbvrBlS+43vaFP4LQHF8HOLZ1GI2y8MU4goj9pisUzsUBtSu7W1qSHv2HrAqL1CSyrCHj9p8TnbdP0l/k48nXTQhLiI16yNMgl0uYtDqdQ4CK+5X0GCApAy3GQRTcrNI4tocrbjwm8U1zjUiqhVBBudLbfxpjGtmoLroA=
    smtp:
      starttls:
        enable: true
      host-gmail: smtp.gmail.com
      host-nuri: mail.nuritelecom.com
      auth: true
      port: 587
